import { Product } from "@/types"

// High quality mobile device images from Unsplash
const img = {
  iphone15Pro: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop",
  iphone15: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&h=600&fit=crop",
  iphone14: "https://images.unsplash.com/photo-1663699459957-1c26d0f6f32f?w=600&h=600&fit=crop",
  iphone13: "https://images.unsplash.com/photo-1632633173522-47456de71b76?w=600&h=600&fit=crop",
  iphoneSE: "https://images.unsplash.com/photo-1624026441011-80d5988c5ec2?w=600&h=600&fit=crop",
  galaxyS24: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&h=600&fit=crop",
  galaxyS23: "https://images.unsplash.com/photo-1678911820864-e5c67e784c28?w=600&h=600&fit=crop",
  galaxyZ: "https://images.unsplash.com/photo-1628744448840-55bdb2497bd4?w=600&h=600&fit=crop",
  galaxyA55: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=600&fit=crop",
  galaxyA35: "https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=600&h=600&fit=crop",
  pixel9: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=600&fit=crop&q=90",
  pixel8: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop&q=90",
  pixel7: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=600&h=600&fit=crop&q=90",
  oneplus12: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=600&h=600&fit=crop",
  oneplus11: "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&h=600&fit=crop",
  oneplusNord: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=600&fit=crop&q=80",
  xiaomi14: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop",
  xiaomi13: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&h=600&fit=crop&q=85",
  redmiNote: "https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=600&h=600&fit=crop&q=85",
  poco: "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&h=600&fit=crop&q=90",
  nothing2: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=600&h=600&fit=crop",
  nothing1: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&h=600&fit=crop&q=70",
  realme: "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&h=600&fit=crop&q=80",
  vivo: "https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=600&h=600&fit=crop&q=80",
  oppo: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=600&h=600&fit=crop&q=90",
  motorola: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=600&fit=crop&q=80",
  sony: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&h=600&fit=crop&q=80",
  huaweiP: "https://images.unsplash.com/photo-1616348436168-de43ad0db179?w=600&h=600&fit=crop&q=80",
  honor: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=600&h=600&fit=crop&q=80",
  asus: "https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=600&h=600&fit=crop&q=70",
  airpodsPro: "https://images.unsplash.com/photo-1606841837239-c5a1a4a07af7?w=600&h=600&fit=crop",
  galaxyBuds: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=600&fit=crop",
  watch: "https://images.unsplash.com/photo-1546868871-af0de0ae72be?w=600&h=600&fit=crop",
  charger: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop",
  case1: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&h=600&fit=crop",
  case2: "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=600&h=600&fit=crop",
  powerbank: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&h=600&fit=crop",
  stand: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&h=600&fit=crop",
  screenGuard: "https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=600&h=600&fit=crop&q=75",
  cable: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&h=600&fit=crop&q=85",
}

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "Flagship",
    price: 134900,
    originalPrice: 159900,
    discountPercentage: 16,
    rating: 4.9,
    reviewCount: 1248,
    description: "The ultimate iPhone with titanium design, A17 Pro chip, and advanced camera system.",
    image: img.iphone15Pro,
    images: [img.iphone15Pro, img.iphone15Pro, img.iphone15Pro],
    inStock: true, stockCount: 15, isNew: true, isFeatured: true,
    specs: { display: "6.7-inch Super Retina XDR OLED", processor: "A17 Pro Bionic", ram: "8GB", storage: "256GB", camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto", battery: "4422mAh with 20W fast charging", os: "iOS 17", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz ProMotion", ipRating: "IP68", weight: "221g" },
    colors: [{ name: "Natural Titanium", hex: "#8A8A8D" }, { name: "Blue Titanium", hex: "#3D4E5C" }, { name: "White Titanium", hex: "#E8E8E3" }, { name: "Black Titanium", hex: "#3E3E3E" }],
    storageOptions: [{ size: "256GB", price: 134900 }, { size: "512GB", price: 154900 }, { size: "1TB", price: 184900 }],
  },
  {
    id: "2",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "Flagship",
    price: 129999,
    originalPrice: 149999,
    discountPercentage: 13,
    rating: 4.8,
    reviewCount: 956,
    description: "Galaxy AI is here. The most powerful Galaxy with S Pen and advanced camera.",
    image: img.galaxyS24,
    inStock: true, stockCount: 22, isSale: true, isFeatured: true,
    specs: { display: "6.8-inch Dynamic AMOLED 2X", processor: "Snapdragon 8 Gen 3", ram: "12GB", storage: "256GB", camera: "200MP Wide + 50MP Periscope + 12MP Ultra Wide + 10MP Telephoto", battery: "5000mAh with 45W super fast charging", os: "Android 14 with One UI 6.1", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "232g" },
    colors: [{ name: "Titanium Gray", hex: "#3C3C3C" }, { name: "Titanium Black", hex: "#1A1A1A" }, { name: "Titanium Violet", hex: "#4B3F5E" }],
    storageOptions: [{ size: "256GB", price: 129999 }, { size: "512GB", price: 139999 }, { size: "1TB", price: 159999 }],
  },
  {
    id: "3",
    name: "Google Pixel 9 Pro",
    brand: "Google",
    category: "Flagship",
    price: 99999,
    originalPrice: 109999,
    discountPercentage: 9,
    rating: 4.7,
    reviewCount: 634,
    description: "Google AI at its best. Amazing camera, pure Android experience.",
    image: img.pixel9,
    inStock: true, stockCount: 18, isFeatured: true,
    specs: { display: "6.7-inch LTPO OLED", processor: "Google Tensor G4", ram: "12GB", storage: "256GB", camera: "50MP Wide + 48MP Ultra Wide + 48MP Telephoto", battery: "5050mAh with 30W fast charging", os: "Android 14", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "210g" },
    colors: [{ name: "Obsidian", hex: "#1E1E1E" }, { name: "Porcelain", hex: "#F1EDE3" }, { name: "Hazel", hex: "#6B6B5D" }],
    storageOptions: [{ size: "128GB", price: 89999 }, { size: "256GB", price: 99999 }, { size: "512GB", price: 119999 }],
  },
  {
    id: "4",
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "Flagship",
    price: 64999,
    rating: 4.6,
    reviewCount: 421,
    description: "Never Settle. Hasselblad camera, blazing fast charging.",
    image: img.oneplus12,
    inStock: true, stockCount: 30,
    specs: { display: "6.82-inch LTPO AMOLED", processor: "Snapdragon 8 Gen 3", ram: "12GB", storage: "256GB", camera: "50MP Main + 64MP Periscope + 48MP Ultra Wide", battery: "5400mAh with 100W SuperVOOC", os: "Android 14 with OxygenOS 14", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP65", weight: "220g" },
    colors: [{ name: "Silky Black", hex: "#1A1A1A" }, { name: "Flowy Emerald", hex: "#2D5C4F" }],
    storageOptions: [{ size: "256GB", price: 64999 }, { size: "512GB", price: 69999 }],
  },
  {
    id: "5",
    name: "Xiaomi 14",
    brand: "Xiaomi",
    category: "Budget",
    price: 59999,
    originalPrice: 69999,
    discountPercentage: 14,
    rating: 4.5,
    reviewCount: 812,
    description: "Leica optics, flagship performance at amazing value.",
    image: img.xiaomi14,
    inStock: true, stockCount: 45, isSale: true,
    specs: { display: "6.36-inch AMOLED", processor: "Snapdragon 8 Gen 3", ram: "8GB", storage: "256GB", camera: "50MP Leica + 50MP Telephoto + 50MP Ultra Wide", battery: "4610mAh with 90W HyperCharge", os: "Android 14 with HyperOS", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "193g" },
    colors: [{ name: "Black", hex: "#000000" }, { name: "White", hex: "#FFFFFF" }, { name: "Jade Green", hex: "#4A7B6E" }],
  },
  {
    id: "6",
    name: "Samsung Galaxy A55",
    brand: "Samsung",
    category: "Budget",
    price: 39999,
    rating: 4.4,
    reviewCount: 567,
    description: "Awesome features, awesome price. Galaxy experience for all.",
    image: img.galaxyA55,
    inStock: true, stockCount: 60,
    specs: { display: "6.6-inch Super AMOLED", processor: "Exynos 1480", ram: "8GB", storage: "128GB", camera: "50MP OIS + 12MP Ultra Wide + 5MP Macro", battery: "5000mAh with 25W fast charging", os: "Android 14 with One UI 6", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP67", weight: "213g" },
    colors: [{ name: "Awesome Navy", hex: "#1E3A5F" }, { name: "Awesome Lilac", hex: "#C8B5D4" }, { name: "Awesome Iceblue", hex: "#A8D8EA" }],
  },
  {
    id: "7",
    name: "AirPods Pro (2nd Gen)",
    brand: "Apple",
    category: "Accessories",
    price: 24900,
    rating: 4.8,
    reviewCount: 2145,
    description: "Active Noise Cancellation, Adaptive Audio, Personalized Spatial Audio.",
    image: img.airpodsPro,
    inStock: true, stockCount: 100, isFeatured: true,
    specs: { battery: "Up to 6 hours listening time", hasWirelessCharging: true, ipRating: "IPX4", weight: "5.3g per earbud", ram: "", storage: "" },
  },
  {
    id: "8",
    name: "Samsung Galaxy Buds2 Pro",
    brand: "Samsung",
    category: "Accessories",
    price: 14999,
    originalPrice: 17999,
    discountPercentage: 17,
    rating: 4.6,
    reviewCount: 892,
    description: "Intelligent ANC, 360 Audio, Hi-Fi sound quality.",
    image: img.galaxyBuds,
    inStock: true, stockCount: 75, isSale: true,
    specs: { battery: "Up to 5 hours with ANC", hasWirelessCharging: true, ipRating: "IPX7", weight: "5.5g per earbud", ram: "", storage: "" },
  },
  {
    id: "9",
    name: "iPhone 14 (Certified Refurbished)",
    brand: "Apple",
    category: "Refurbished",
    price: 59999,
    originalPrice: 79900,
    discountPercentage: 25,
    rating: 4.7,
    reviewCount: 345,
    description: "Like new condition with full warranty. Thoroughly tested and certified.",
    image: img.iphone14,
    inStock: true, stockCount: 12, isSale: true,
    specs: { display: "6.1-inch Super Retina XDR", processor: "A15 Bionic", ram: "6GB", storage: "128GB", camera: "12MP Dual Camera", battery: "3279mAh", os: "iOS 17", is5G: true, hasWirelessCharging: true, refreshRate: "60Hz", ipRating: "IP68" },
  },
  {
    id: "10",
    name: "Google Pixel 8a",
    brand: "Google",
    category: "Budget",
    price: 52999,
    rating: 4.5,
    reviewCount: 423,
    description: "Google AI features at an amazing price. Best camera in class.",
    image: img.pixel8,
    inStock: true, stockCount: 35, isNew: true,
    specs: { display: "6.1-inch OLED", processor: "Google Tensor G3", ram: "8GB", storage: "128GB", camera: "64MP Wide + 13MP Ultra Wide", battery: "4492mAh with 18W charging", os: "Android 14", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP67", weight: "188g" },
    colors: [{ name: "Obsidian", hex: "#1E1E1E" }, { name: "Porcelain", hex: "#F1EDE3" }, { name: "Bay", hex: "#6FA8DC" }, { name: "Mint", hex: "#A8E6CF" }],
  },
  // ─── 11-20: More Flagships & Premium ─────────────────────────
  {
    id: "11",
    name: "iPhone 15",
    brand: "Apple",
    category: "Flagship",
    price: 79900,
    originalPrice: 89900,
    discountPercentage: 11,
    rating: 4.7,
    reviewCount: 1032,
    description: "Dynamic Island, 48MP camera, and USB-C. The new standard for iPhone.",
    image: img.iphone15,
    inStock: true, stockCount: 40, isNew: true, isFeatured: true,
    specs: { display: "6.1-inch Super Retina XDR OLED", processor: "A16 Bionic", ram: "6GB", storage: "128GB", camera: "48MP Main + 12MP Ultra Wide", battery: "3877mAh", os: "iOS 17", is5G: true, hasWirelessCharging: true, refreshRate: "60Hz", ipRating: "IP68", weight: "171g" },
    colors: [{ name: "Blue", hex: "#6FA8DC" }, { name: "Pink", hex: "#F4C2C2" }, { name: "Yellow", hex: "#FDDA0D" }, { name: "Green", hex: "#7CB342" }, { name: "Black", hex: "#1A1A1A" }],
    storageOptions: [{ size: "128GB", price: 79900 }, { size: "256GB", price: 89900 }, { size: "512GB", price: 109900 }],
  },
  {
    id: "12",
    name: "Samsung Galaxy Z Fold6",
    brand: "Samsung",
    category: "Flagship",
    price: 164999,
    originalPrice: 179999,
    discountPercentage: 8,
    rating: 4.6,
    reviewCount: 312,
    description: "Galaxy AI with the ultimate foldable experience. PC-like multitasking on the go.",
    image: img.galaxyZ,
    inStock: true, stockCount: 10, isNew: true, isFeatured: true,
    specs: { display: "7.6-inch Dynamic AMOLED 2X (Foldable)", processor: "Snapdragon 8 Gen 3", ram: "12GB", storage: "256GB", camera: "50MP Wide + 12MP Ultra Wide + 10MP Telephoto", battery: "4400mAh with 25W fast charging", os: "Android 14 with One UI 6.1", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IPX8", weight: "239g" },
    colors: [{ name: "Navy", hex: "#1E3A5F" }, { name: "Silver Shadow", hex: "#C0C0C0" }, { name: "Pink", hex: "#F4C2C2" }],
    storageOptions: [{ size: "256GB", price: 164999 }, { size: "512GB", price: 179999 }, { size: "1TB", price: 199999 }],
  },
  {
    id: "13",
    name: "Samsung Galaxy Z Flip6",
    brand: "Samsung",
    category: "Flagship",
    price: 109999,
    originalPrice: 119999,
    discountPercentage: 8,
    rating: 4.5,
    reviewCount: 478,
    description: "Compact foldable style with Galaxy AI. The statement phone.",
    image: img.galaxyZ,
    inStock: true, stockCount: 25, isNew: true,
    specs: { display: "6.7-inch Dynamic AMOLED 2X (Foldable)", processor: "Snapdragon 8 Gen 3", ram: "12GB", storage: "256GB", camera: "50MP Wide + 12MP Ultra Wide", battery: "4000mAh with 25W fast charging", os: "Android 14 with One UI 6.1", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IPX8", weight: "187g" },
    colors: [{ name: "Mint", hex: "#A8E6CF" }, { name: "Silver Shadow", hex: "#C0C0C0" }, { name: "Yellow", hex: "#FDDA0D" }, { name: "Blue", hex: "#6FA8DC" }],
    storageOptions: [{ size: "256GB", price: 109999 }, { size: "512GB", price: 119999 }],
  },
  {
    id: "14",
    name: "Nothing Phone (2)",
    brand: "Nothing",
    category: "Flagship",
    price: 44999,
    rating: 4.4,
    reviewCount: 654,
    description: "Unique Glyph Interface. Transparent design meets premium performance.",
    image: img.nothing2,
    inStock: true, stockCount: 28, isFeatured: true,
    specs: { display: "6.7-inch LTPO AMOLED", processor: "Snapdragon 8+ Gen 1", ram: "12GB", storage: "256GB", camera: "50MP Dual Camera with OIS", battery: "4700mAh with 45W charging", os: "Android 14 with Nothing OS 2.5", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP54", weight: "201g" },
    colors: [{ name: "White", hex: "#FFFFFF" }, { name: "Dark Grey", hex: "#3E3E3E" }],
    storageOptions: [{ size: "128GB", price: 44999 }, { size: "256GB", price: 49999 }],
  },
  {
    id: "15",
    name: "Samsung Galaxy S23 FE",
    brand: "Samsung",
    category: "Flagship",
    price: 49999,
    originalPrice: 59999,
    discountPercentage: 17,
    rating: 4.5,
    reviewCount: 789,
    description: "Fan Edition with flagship features. Galaxy experience at a great price.",
    image: img.galaxyS23,
    inStock: true, stockCount: 35, isSale: true,
    specs: { display: "6.4-inch Dynamic AMOLED 2X", processor: "Exynos 2200", ram: "8GB", storage: "128GB", camera: "50MP Triple Camera with OIS", battery: "4500mAh with 25W fast charging", os: "Android 14 with One UI 6", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "209g" },
    colors: [{ name: "Mint", hex: "#A8E6CF" }, { name: "Cream", hex: "#FFFDD0" }, { name: "Graphite", hex: "#3C3C3C" }],
    storageOptions: [{ size: "128GB", price: 49999 }, { size: "256GB", price: 54999 }],
  },
  {
    id: "16",
    name: "Google Pixel 9",
    brand: "Google",
    category: "Flagship",
    price: 79999,
    rating: 4.6,
    reviewCount: 512,
    description: "Pure Google AI experience. Best-in-class photography and smart features.",
    image: img.pixel9,
    inStock: true, stockCount: 20, isNew: true,
    specs: { display: "6.3-inch OLED", processor: "Google Tensor G4", ram: "12GB", storage: "128GB", camera: "50MP Wide + 48MP Ultra Wide", battery: "4700mAh with 27W charging", os: "Android 15", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "198g" },
    colors: [{ name: "Obsidian", hex: "#1E1E1E" }, { name: "Porcelain", hex: "#F1EDE3" }, { name: "Wintergreen", hex: "#A8E6CF" }, { name: "Peony", hex: "#F4C2C2" }],
    storageOptions: [{ size: "128GB", price: 79999 }, { size: "256GB", price: 89999 }],
  },
  {
    id: "17",
    name: "OnePlus 12R",
    brand: "OnePlus",
    category: "Flagship",
    price: 42999,
    rating: 4.5,
    reviewCount: 367,
    description: "Performance beast. Flagship speed at a smart price.",
    image: img.oneplus11,
    inStock: true, stockCount: 50,
    specs: { display: "6.78-inch LTPO AMOLED", processor: "Snapdragon 8 Gen 2", ram: "8GB", storage: "128GB", camera: "50MP Sony IMX890 + 8MP Ultra Wide + 2MP Macro", battery: "5500mAh with 100W SUPERVOOC", os: "Android 14 with OxygenOS 14", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP65", weight: "207g" },
    colors: [{ name: "Iron Gray", hex: "#4A4A4A" }, { name: "Cool Blue", hex: "#6FA8DC" }],
    storageOptions: [{ size: "128GB", price: 42999 }, { size: "256GB", price: 47999 }],
  },
  {
    id: "18",
    name: "iPhone 13 (Refurbished)",
    brand: "Apple",
    category: "Refurbished",
    price: 44999,
    originalPrice: 69900,
    discountPercentage: 36,
    rating: 4.6,
    reviewCount: 892,
    description: "Certified refurbished with full warranty. Incredible value.",
    image: img.iphone13,
    inStock: true, stockCount: 20, isSale: true,
    specs: { display: "6.1-inch Super Retina XDR", processor: "A15 Bionic", ram: "4GB", storage: "128GB", camera: "12MP Dual Camera", battery: "3240mAh", os: "iOS 17", is5G: true, hasWirelessCharging: true, refreshRate: "60Hz", ipRating: "IP68", weight: "174g" },
    colors: [{ name: "Midnight", hex: "#1A1A1A" }, { name: "Starlight", hex: "#F1EDE3" }, { name: "Blue", hex: "#6FA8DC" }, { name: "Pink", hex: "#F4C2C2" }],
  },
  {
    id: "19",
    name: "Xiaomi 13 Pro",
    brand: "Xiaomi",
    category: "Flagship",
    price: 49999,
    originalPrice: 69999,
    discountPercentage: 29,
    rating: 4.5,
    reviewCount: 543,
    description: "Leica optics, 1-inch sensor, flagship performance at incredible price.",
    image: img.xiaomi13,
    inStock: true, stockCount: 18, isSale: true,
    specs: { display: "6.73-inch LTPO AMOLED", processor: "Snapdragon 8 Gen 2", ram: "12GB", storage: "256GB", camera: "50MP 1-inch Leica + 50MP Telephoto + 50MP Ultra Wide", battery: "4820mAh with 120W HyperCharge", os: "Android 13 with MIUI 14", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "229g" },
    colors: [{ name: "Ceramic Black", hex: "#1A1A1A" }, { name: "Ceramic White", hex: "#F5F5F5" }, { name: "Flora Green", hex: "#7CB342" }],
  },
  {
    id: "20",
    name: "Google Pixel 7 Pro (Refurbished)",
    brand: "Google",
    category: "Refurbished",
    price: 39999,
    originalPrice: 84999,
    discountPercentage: 53,
    rating: 4.4,
    reviewCount: 234,
    description: "Premium refurbished Pixel with amazing camera and 5 years of updates.",
    image: img.pixel7,
    inStock: true, stockCount: 8, isSale: true,
    specs: { display: "6.7-inch LTPO OLED", processor: "Google Tensor G2", ram: "12GB", storage: "128GB", camera: "50MP Wide + 12MP Ultra Wide + 48MP Telephoto", battery: "5000mAh with 30W charging", os: "Android 14", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "212g" },
  },
  // ─── 21-30: Budget & Mid-range ────────────────────────────────
  {
    id: "21",
    name: "Redmi Note 13 Pro+",
    brand: "Xiaomi",
    category: "Budget",
    price: 29999,
    originalPrice: 34999,
    discountPercentage: 14,
    rating: 4.4,
    reviewCount: 1567,
    description: "200MP camera, 120W charging. The ultimate Redmi experience.",
    image: img.redmiNote,
    inStock: true, stockCount: 80, isSale: true,
    specs: { display: "6.67-inch AMOLED", processor: "MediaTek Dimensity 7200", ram: "8GB", storage: "256GB", camera: "200MP Main + 8MP Ultra Wide + 2MP Macro", battery: "5000mAh with 120W HyperCharge", os: "Android 13 with MIUI 14", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP68", weight: "204g" },
    colors: [{ name: "Moonlight White", hex: "#F5F5F5" }, { name: "Midnight Black", hex: "#1A1A1A" }, { name: "Aurora Purple", hex: "#7B4D8E" }],
  },
  {
    id: "22",
    name: "POCO F6",
    brand: "Xiaomi",
    category: "Budget",
    price: 24999,
    rating: 4.3,
    reviewCount: 1234,
    description: "Flagship killer. Top specs at an unreal price point.",
    image: img.poco,
    inStock: true, stockCount: 90, isFeatured: true,
    specs: { display: "6.67-inch AMOLED", processor: "Snapdragon 8s Gen 3", ram: "8GB", storage: "256GB", camera: "50MP OIS + 8MP Ultra Wide", battery: "5000mAh with 90W turbo charging", os: "Android 14 with HyperOS", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP54", weight: "179g" },
    colors: [{ name: "Black", hex: "#1A1A1A" }, { name: "Green", hex: "#4A7B6E" }, { name: "White", hex: "#F5F5F5" }],
  },
  {
    id: "23",
    name: "Samsung Galaxy A35",
    brand: "Samsung",
    category: "Budget",
    price: 29999,
    rating: 4.3,
    reviewCount: 876,
    description: "Awesome Galaxy experience with 5G. Style meets substance.",
    image: img.galaxyA35,
    inStock: true, stockCount: 55,
    specs: { display: "6.6-inch Super AMOLED", processor: "Exynos 1380", ram: "6GB", storage: "128GB", camera: "50MP OIS + 8MP Ultra Wide + 5MP Macro", battery: "5000mAh with 25W fast charging", os: "Android 14 with One UI 6", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP67", weight: "209g" },
    colors: [{ name: "Awesome Lilac", hex: "#C8B5D4" }, { name: "Awesome Navy", hex: "#1E3A5F" }, { name: "Awesome Iceblue", hex: "#A8D8EA" }],
  },
  {
    id: "24",
    name: "OnePlus Nord CE 4",
    brand: "OnePlus",
    category: "Budget",
    price: 24999,
    rating: 4.2,
    reviewCount: 543,
    description: "The essential OnePlus experience. Fast, smooth, and affordable.",
    image: img.oneplusNord,
    inStock: true, stockCount: 65,
    specs: { display: "6.7-inch AMOLED", processor: "Snapdragon 7 Gen 3", ram: "8GB", storage: "128GB", camera: "50MP Sony + 8MP Ultra Wide", battery: "5500mAh with 100W SUPERVOOC", os: "Android 14 with OxygenOS 14", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP65", weight: "184g" },
    colors: [{ name: "Dark Chrome", hex: "#3C3C3C" }, { name: "Celadon Marble", hex: "#ACE1AF" }],
  },
  {
    id: "25",
    name: "realme GT 6",
    brand: "Realme",
    category: "Budget",
    price: 31999,
    rating: 4.3,
    reviewCount: 456,
    description: "Flagship performance on a budget. Next-gen Snapdragon power.",
    image: img.realme,
    inStock: true, stockCount: 40,
    specs: { display: "6.78-inch LTPO AMOLED", processor: "Snapdragon 8s Gen 3", ram: "8GB", storage: "256GB", camera: "50MP Sony LYT-808 + 8MP Ultra Wide", battery: "5500mAh with 120W SUPERVOOC", os: "Android 14 with realme UI 5.0", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP65", weight: "199g" },
    colors: [{ name: "Razor Green", hex: "#2D5C4F" }, { name: "Fluid Silver", hex: "#C0C0C0" }],
  },
  {
    id: "26",
    name: "vivo V30 Pro",
    brand: "Vivo",
    category: "Budget",
    price: 39999,
    originalPrice: 44999,
    discountPercentage: 11,
    rating: 4.4,
    reviewCount: 678,
    description: "ZEISS portrait mastery. Aura light for stunning selfies.",
    image: img.vivo,
    inStock: true, stockCount: 30, isSale: true,
    specs: { display: "6.78-inch AMOLED", processor: "MediaTek Dimensity 8200", ram: "8GB", storage: "256GB", camera: "50MP ZEISS Main + 50MP Ultra Wide + 50MP Telephoto", battery: "5000mAh with 80W FlashCharge", os: "Android 14 with Funtouch OS 14", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP54", weight: "187g" },
    colors: [{ name: "Peacock Green", hex: "#006B54" }, { name: "Noble Red", hex: "#C41E3A" }],
  },
  {
    id: "27",
    name: "OPPO Reno 12 Pro",
    brand: "OPPO",
    category: "Budget",
    price: 36999,
    rating: 4.3,
    reviewCount: 345,
    description: "AI-powered photography. Stunning design with premium features.",
    image: img.oppo,
    inStock: true, stockCount: 45, isNew: true,
    specs: { display: "6.7-inch AMOLED", processor: "MediaTek Dimensity 7300", ram: "12GB", storage: "256GB", camera: "50MP Sony + 50MP Telephoto + 8MP Ultra Wide", battery: "5000mAh with 80W SUPERVOOC", os: "Android 14 with ColorOS 14", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP65", weight: "180g" },
    colors: [{ name: "Nebula Silver", hex: "#C0C0C0" }, { name: "Space Brown", hex: "#5D4037" }],
  },
  {
    id: "28",
    name: "Nothing Phone (1) Refurbished",
    brand: "Nothing",
    category: "Refurbished",
    price: 19999,
    originalPrice: 33999,
    discountPercentage: 41,
    rating: 4.2,
    reviewCount: 567,
    description: "The iconic transparent design. Certified refurbished with warranty.",
    image: img.nothing1,
    inStock: true, stockCount: 15, isSale: true,
    specs: { display: "6.55-inch OLED", processor: "Snapdragon 778G+", ram: "8GB", storage: "128GB", camera: "50MP Dual Camera", battery: "4500mAh with 33W charging", os: "Android 14 with Nothing OS 2.5", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP53", weight: "193g" },
  },
  {
    id: "29",
    name: "Motorola Edge 50 Pro",
    brand: "Motorola",
    category: "Budget",
    price: 29999,
    rating: 4.3,
    reviewCount: 432,
    description: "AI-powered features with military-grade durability and clean Android.",
    image: img.motorola,
    inStock: true, stockCount: 35,
    specs: { display: "6.7-inch pOLED", processor: "Snapdragon 7 Gen 3", ram: "8GB", storage: "256GB", camera: "50MP OIS + 13MP Ultra Wide + 10MP Telephoto", battery: "4500mAh with 125W TurboPower", os: "Android 14 with My UX", is5G: true, hasWirelessCharging: true, refreshRate: "144Hz", ipRating: "IP68", weight: "186g" },
    colors: [{ name: "Moonlight Pearl", hex: "#F5F5F5" }, { name: "Black Beauty", hex: "#1A1A1A" }, { name: "Luxe Lavender", hex: "#C8B5D4" }],
  },
  {
    id: "30",
    name: "Redmi Note 13",
    brand: "Xiaomi",
    category: "Budget",
    price: 14999,
    originalPrice: 17999,
    discountPercentage: 17,
    rating: 4.2,
    reviewCount: 2345,
    description: "Best budget phone under 15K. AMOLED display and 108MP camera.",
    image: img.redmiNote,
    inStock: true, stockCount: 120, isSale: true,
    specs: { display: "6.67-inch AMOLED", processor: "Snapdragon 685", ram: "6GB", storage: "128GB", camera: "108MP Main + 8MP Ultra Wide + 2MP Macro", battery: "5000mAh with 33W fast charging", os: "Android 13 with MIUI 14", is5G: false, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP54", weight: "188g" },
    colors: [{ name: "Midnight Black", hex: "#1A1A1A" }, { name: "Arctic White", hex: "#F5F5F5" }, { name: "Ocean Teal", hex: "#4A7B6E" }],
  },
  // ─── 31-40: More Phones + Premium Accessories ─────────────────
  {
    id: "31",
    name: "Sony Xperia 1 VI",
    brand: "Sony",
    category: "Flagship",
    price: 109999,
    rating: 4.5,
    reviewCount: 189,
    description: "Pro-level camera with Alpha technology. 4K OLED cinematic display.",
    image: img.sony,
    inStock: true, stockCount: 8, isNew: true,
    specs: { display: "6.5-inch 4K OLED", processor: "Snapdragon 8 Gen 3", ram: "12GB", storage: "256GB", camera: "48MP Exmor T + 12MP Ultra Wide + 12MP Telephoto", battery: "5000mAh with 30W charging", os: "Android 14", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "192g" },
    colors: [{ name: "Black", hex: "#1A1A1A" }, { name: "Platinum Silver", hex: "#E5E5E5" }],
    storageOptions: [{ size: "256GB", price: 109999 }, { size: "512GB", price: 124999 }],
  },
  {
    id: "32",
    name: "Huawei P60 Pro",
    brand: "Huawei",
    category: "Flagship",
    price: 84999,
    rating: 4.5,
    reviewCount: 234,
    description: "XMAGE camera system. Ultra lighting photography champion.",
    image: img.huaweiP,
    inStock: true, stockCount: 12,
    specs: { display: "6.67-inch LTPO OLED", processor: "Snapdragon 8+ Gen 1", ram: "12GB", storage: "256GB", camera: "48MP XMAGE + 13MP Ultra Wide + 48MP Periscope", battery: "4815mAh with 88W charging", os: "HarmonyOS 4", is5G: false, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "200g" },
    colors: [{ name: "Black", hex: "#1A1A1A" }, { name: "Rococo Pearl", hex: "#F5EFE7" }, { name: "Green", hex: "#4A7B6E" }],
  },
  {
    id: "33",
    name: "Honor Magic6 Pro",
    brand: "Honor",
    category: "Flagship",
    price: 59999,
    originalPrice: 69999,
    discountPercentage: 14,
    rating: 4.5,
    reviewCount: 298,
    description: "AI-powered MagicOS. Falcon camera system with silicon-carbon battery.",
    image: img.honor,
    inStock: true, stockCount: 20, isSale: true,
    specs: { display: "6.78-inch LTPO OLED", processor: "Snapdragon 8 Gen 3", ram: "12GB", storage: "256GB", camera: "50MP Wide + 50MP Ultra Wide + 180MP Periscope", battery: "5600mAh with 80W charging", os: "Android 14 with MagicOS 8.0", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "225g" },
    colors: [{ name: "Epic Green", hex: "#2D5C4F" }, { name: "Moonlight Black", hex: "#1A1A1A" }],
  },
  {
    id: "34",
    name: "ASUS ROG Phone 8 Pro",
    brand: "ASUS",
    category: "Flagship",
    price: 89999,
    rating: 4.7,
    reviewCount: 312,
    description: "Ultimate gaming phone. AirTrigger ultrasonic controls and vapor chamber cooling.",
    image: img.asus,
    inStock: true, stockCount: 10, isFeatured: true,
    specs: { display: "6.78-inch Samsung AMOLED", processor: "Snapdragon 8 Gen 3", ram: "16GB", storage: "512GB", camera: "50MP Sony IMX890 + 13MP Ultra Wide + 32MP Telephoto", battery: "5500mAh with 65W HyperCharge", os: "Android 14 with ROG UI", is5G: true, hasWirelessCharging: false, refreshRate: "165Hz", ipRating: "IP68", weight: "225g" },
    colors: [{ name: "Phantom Black", hex: "#0D0D0D" }],
    storageOptions: [{ size: "256GB", price: 79999 }, { size: "512GB", price: 89999 }],
  },
  {
    id: "35",
    name: "iPhone SE (Refurbished)",
    brand: "Apple",
    category: "Refurbished",
    price: 24999,
    originalPrice: 49900,
    discountPercentage: 50,
    rating: 4.3,
    reviewCount: 1234,
    description: "Compact powerhouse. A15 chip in the beloved SE design.",
    image: img.iphoneSE,
    inStock: true, stockCount: 25, isSale: true,
    specs: { display: "4.7-inch Retina HD", processor: "A15 Bionic", ram: "4GB", storage: "64GB", camera: "12MP Wide", battery: "2018mAh", os: "iOS 17", is5G: true, hasWirelessCharging: true, refreshRate: "60Hz", ipRating: "IP67", weight: "144g" },
    colors: [{ name: "Midnight", hex: "#1A1A1A" }, { name: "Starlight", hex: "#F1EDE3" }, { name: "(PRODUCT)RED", hex: "#C41E3A" }],
  },
  {
    id: "36",
    name: "Apple Watch Ultra 2",
    brand: "Apple",
    category: "Accessories",
    price: 89900,
    rating: 4.8,
    reviewCount: 567,
    description: "The most capable Apple Watch ever. Titanium case, precision GPS, 36-hour battery.",
    image: img.watch,
    inStock: true, stockCount: 15, isNew: true, isFeatured: true,
    specs: { display: "49mm Always-On Retina LTPO OLED", battery: "Up to 36 hours", hasWirelessCharging: true, ipRating: "WR100 + EN13319", weight: "61.4g", ram: "", storage: "" },
  },
  {
    id: "37",
    name: "Samsung 45W Super Fast Charger",
    brand: "Samsung",
    category: "Accessories",
    price: 2999,
    originalPrice: 3999,
    discountPercentage: 25,
    rating: 4.6,
    reviewCount: 2341,
    description: "Official 45W charger for Galaxy S24 series. USB-C PD 3.0.",
    image: img.charger,
    inStock: true, stockCount: 200, isSale: true,
    specs: { weight: "98g", ram: "", storage: "" },
  },
  {
    id: "38",
    name: "Spigen Ultra Hybrid Case - iPhone 15 Pro",
    brand: "Spigen",
    category: "Accessories",
    price: 1499,
    rating: 4.5,
    reviewCount: 3456,
    description: "Crystal clear protection with Air Cushion technology. MIL-STD 810G certified.",
    image: img.case1,
    inStock: true, stockCount: 300,
    specs: { weight: "35g", ram: "", storage: "" },
  },
  {
    id: "39",
    name: "Anker 20000mAh Power Bank",
    brand: "Anker",
    category: "Accessories",
    price: 3499,
    originalPrice: 4499,
    discountPercentage: 22,
    rating: 4.7,
    reviewCount: 4567,
    description: "PowerIQ 3.0 with 65W USB-C PD. Charge your phone 4 times.",
    image: img.powerbank,
    inStock: true, stockCount: 150, isSale: true,
    specs: { weight: "350g", battery: "20000mAh with 65W PD output", ram: "", storage: "" },
  },
  {
    id: "40",
    name: "Samsung Galaxy Watch6 Classic",
    brand: "Samsung",
    category: "Accessories",
    price: 34999,
    originalPrice: 39999,
    discountPercentage: 13,
    rating: 4.6,
    reviewCount: 678,
    description: "Rotating bezel with advanced health monitoring and Wear OS.",
    image: img.watch,
    inStock: true, stockCount: 20, isSale: true,
    specs: { display: "1.47-inch Super AMOLED", battery: "Up to 40 hours", hasWirelessCharging: true, ipRating: "IP68 + 5ATM + MIL-STD-810H", weight: "59g", ram: "", storage: "" },
  },
  // ─── 41-50: More variety ──────────────────────────────────────
  {
    id: "41",
    name: "vivo X100 Pro",
    brand: "Vivo",
    category: "Flagship",
    price: 89999,
    rating: 4.6,
    reviewCount: 345,
    description: "ZEISS APO telephoto. The new benchmark in mobile photography.",
    image: img.vivo,
    inStock: true, stockCount: 12, isNew: true, isFeatured: true,
    specs: { display: "6.78-inch LTPO AMOLED", processor: "MediaTek Dimensity 9300", ram: "16GB", storage: "256GB", camera: "50MP ZEISS + 50MP Ultra Wide + 64MP APO Periscope", battery: "5400mAh with 100W FlashCharge", os: "Android 14 with Funtouch OS 14", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "221g" },
    colors: [{ name: "Asteroid Black", hex: "#1A1A1A" }, { name: "Stardust Blue", hex: "#6FA8DC" }],
  },
  {
    id: "42",
    name: "OPPO Find X7 Ultra",
    brand: "OPPO",
    category: "Flagship",
    price: 99999,
    rating: 4.7,
    reviewCount: 234,
    description: "Dual periscope camera system. Hasselblad color science mastery.",
    image: img.oppo,
    inStock: true, stockCount: 8, isNew: true,
    specs: { display: "6.82-inch LTPO AMOLED", processor: "Snapdragon 8 Gen 3", ram: "16GB", storage: "256GB", camera: "50MP + 50MP Ultra Wide + 50MP 3x + 50MP 6x Periscope", battery: "5600mAh with 100W SUPERVOOC", os: "Android 14 with ColorOS 14", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "221g" },
    colors: [{ name: "Hasselblad Brown", hex: "#5D4037" }, { name: "Ocean Blue", hex: "#4A7B9D" }],
  },
  {
    id: "43",
    name: "realme 12 Pro+ 5G",
    brand: "Realme",
    category: "Budget",
    price: 24999,
    rating: 4.3,
    reviewCount: 789,
    description: "Luxury watchstrap design with periscope telephoto camera.",
    image: img.realme,
    inStock: true, stockCount: 50,
    specs: { display: "6.7-inch AMOLED", processor: "Snapdragon 7s Gen 2", ram: "8GB", storage: "128GB", camera: "50MP Sony IMX890 + 64MP Periscope + 8MP Ultra Wide", battery: "5000mAh with 67W SUPERVOOC", os: "Android 14 with realme UI 5.0", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP65", weight: "190g" },
    colors: [{ name: "Submarine Blue", hex: "#2E4057" }, { name: "Navigator Beige", hex: "#D4C4A8" }],
  },
  {
    id: "44",
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    category: "Flagship",
    price: 74999,
    originalPrice: 79999,
    discountPercentage: 6,
    rating: 4.6,
    reviewCount: 867,
    description: "Galaxy AI in a compact flagship. Pro-grade camera with Nightography.",
    image: img.galaxyS24,
    inStock: true, stockCount: 30, isSale: true,
    specs: { display: "6.2-inch Dynamic AMOLED 2X", processor: "Exynos 2400", ram: "8GB", storage: "128GB", camera: "50MP Wide + 12MP Ultra Wide + 10MP Telephoto", battery: "4000mAh with 25W fast charging", os: "Android 14 with One UI 6.1", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "167g" },
    colors: [{ name: "Onyx Black", hex: "#1A1A1A" }, { name: "Marble Gray", hex: "#8A8A8D" }, { name: "Cobalt Violet", hex: "#4B3F5E" }, { name: "Amber Yellow", hex: "#FDDA0D" }],
    storageOptions: [{ size: "128GB", price: 74999 }, { size: "256GB", price: 79999 }],
  },
  {
    id: "45",
    name: "Dbrand Grip Case - Galaxy S24 Ultra",
    brand: "dbrand",
    category: "Accessories",
    price: 2499,
    rating: 4.7,
    reviewCount: 1234,
    description: "Military-grade drop protection with customizable skins.",
    image: img.case2,
    inStock: true, stockCount: 100,
    specs: { weight: "40g", ram: "", storage: "" },
  },
  {
    id: "46",
    name: "Samsung Galaxy S23 Ultra (Refurbished)",
    brand: "Samsung",
    category: "Refurbished",
    price: 64999,
    originalPrice: 124999,
    discountPercentage: 48,
    rating: 4.7,
    reviewCount: 456,
    description: "Like-new condition. Full 200MP camera system with S Pen.",
    image: img.galaxyS23,
    inStock: true, stockCount: 8, isSale: true,
    specs: { display: "6.8-inch Dynamic AMOLED 2X", processor: "Snapdragon 8 Gen 2", ram: "12GB", storage: "256GB", camera: "200MP Wide + 12MP Ultra Wide + 10MP Telephoto + 10MP Periscope", battery: "5000mAh with 45W charging", os: "Android 14 with One UI 6.1", is5G: true, hasWirelessCharging: true, refreshRate: "120Hz", ipRating: "IP68", weight: "234g" },
  },
  {
    id: "47",
    name: "MagSafe Wireless Charger Stand",
    brand: "Apple",
    category: "Accessories",
    price: 4500,
    rating: 4.5,
    reviewCount: 2345,
    description: "Perfectly aligned wireless charging for iPhone. Fast 15W MagSafe.",
    image: img.stand,
    inStock: true, stockCount: 80,
    specs: { weight: "150g", hasWirelessCharging: true, ram: "", storage: "" },
  },
  {
    id: "48",
    name: "OnePlus 11 (Refurbished)",
    brand: "OnePlus",
    category: "Refurbished",
    price: 29999,
    originalPrice: 56999,
    discountPercentage: 47,
    rating: 4.4,
    reviewCount: 543,
    description: "Flagship performance refurbished. Hasselblad camera and 100W charging.",
    image: img.oneplus11,
    inStock: true, stockCount: 12, isSale: true,
    specs: { display: "6.7-inch LTPO AMOLED", processor: "Snapdragon 8 Gen 2", ram: "16GB", storage: "256GB", camera: "50MP Hasselblad + 32MP Telephoto + 48MP Ultra Wide", battery: "5000mAh with 100W SUPERVOOC", os: "Android 14 with OxygenOS 14", is5G: true, hasWirelessCharging: false, refreshRate: "120Hz", ipRating: "IP65", weight: "205g" },
  },
  {
    id: "49",
    name: "Tempered Glass Screen Guard - Universal",
    brand: "Spigen",
    category: "Accessories",
    price: 999,
    originalPrice: 1499,
    discountPercentage: 33,
    rating: 4.3,
    reviewCount: 8765,
    description: "9H hardness anti-scratch tempered glass. Crystal HD clarity.",
    image: img.screenGuard,
    inStock: true, stockCount: 500, isSale: true,
    specs: { weight: "12g", ram: "", storage: "" },
  },
  {
    id: "50",
    name: "USB-C to Lightning Cable (2m)",
    brand: "Apple",
    category: "Accessories",
    price: 1900,
    rating: 4.4,
    reviewCount: 3456,
    description: "Official Apple cable. Supports fast charging and data sync.",
    image: img.cable,
    inStock: true, stockCount: 250,
    specs: { weight: "28g", ram: "", storage: "" },
  },
]

export const getBrandColor = (brand: string): string => {
  const colors: Record<string, string> = {
    Apple: "bg-zinc-100 text-zinc-900 dark:bg-zinc-800 dark:text-zinc-100",
    Samsung: "bg-blue-100 text-blue-900 dark:bg-blue-900 dark:text-blue-100",
    Google: "bg-green-100 text-green-900 dark:bg-green-900 dark:text-green-100",
    OnePlus: "bg-red-100 text-red-900 dark:bg-red-900 dark:text-red-100",
    Xiaomi: "bg-orange-100 text-orange-900 dark:bg-orange-900 dark:text-orange-100",
    Huawei: "bg-purple-100 text-purple-900 dark:bg-purple-900 dark:text-purple-100",
    Sony: "bg-indigo-100 text-indigo-900 dark:bg-indigo-900 dark:text-indigo-100",
    Nothing: "bg-zinc-100 text-zinc-900 dark:bg-zinc-800 dark:text-zinc-100",
    Vivo: "bg-sky-100 text-sky-900 dark:bg-sky-900 dark:text-sky-100",
    OPPO: "bg-emerald-100 text-emerald-900 dark:bg-emerald-900 dark:text-emerald-100",
    Realme: "bg-yellow-100 text-yellow-900 dark:bg-yellow-900 dark:text-yellow-100",
    Motorola: "bg-cyan-100 text-cyan-900 dark:bg-cyan-900 dark:text-cyan-100",
    Honor: "bg-teal-100 text-teal-900 dark:bg-teal-900 dark:text-teal-100",
    ASUS: "bg-rose-100 text-rose-900 dark:bg-rose-900 dark:text-rose-100",
    Spigen: "bg-slate-100 text-slate-900 dark:bg-slate-800 dark:text-slate-100",
    Anker: "bg-blue-100 text-blue-900 dark:bg-blue-900 dark:text-blue-100",
    dbrand: "bg-zinc-100 text-zinc-900 dark:bg-zinc-800 dark:text-zinc-100",
  }
  return colors[brand] || "bg-muted text-muted-foreground"
}

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(price)
}
